@startuml
component uart
component sensor
component neopixels
component gwcmd
component notifier
boundary Timer
notifier -(0- neopixels : neopixels => ctrl
notifier -(0- gwcmd : gateway => gateway
notifier -(0- sensor : sensor => ctrl
gwcmd -(0- uart : blerx => rx
gwcmd -(0- uart : bletx => tx
neopixels .. Timer : clock
sensor .. Timer : clock
notifier .. Timer : clock
@enduml