@startuml
skinparam defaultTextAlignment left
[*] --> BLENotifierSC
state BLENotifierSC{
state Init{
	Init : entry / do \n...\nend\n

Init --> Ready : t:clock?timer_timeout[t.id == 0]\naction breath()\n
}
state Ready{

Ready --> Measuring : sensor?pumping\naction pump()\n
	Ready : gateway?request_measurement / \naction pulse()\n
}
state Measuring{

Measuring --> WaitGatewayAck : sensor?idle
	Measuring : sensor?measuring / \naction measure()\n
	Measuring : sensor?pumping / \naction pump()\n
}
state WaitGatewayAck{
	WaitGatewayAck : entry / do \n...\nend\n

WaitGatewayAck --> GatewayError : t:clock?timer_timeout[t.id == 0]

WaitGatewayAck --> GatewayError : gateway?bad_measurement

WaitGatewayAck --> WaitServerAck : gateway?measurement_received
}
state GatewayError{
	GatewayError : entry / do \n...\nend\n

GatewayError --> Ready : t:clock?timer_timeout[t.id == 0]\naction pulse()\n
}
state WaitServerAck{
	WaitServerAck : entry / do \n...\nend\n

WaitServerAck --> ServerError : t:clock?timer_timeout[t.id == 0]

WaitServerAck --> Ready : gateway?measurement_stored\naction breath()\n
}
state ServerError{
	ServerError : entry / do \n...\nend\n

ServerError --> Ready : t:clock?timer_timeout[t.id == 0]\naction breath()\n
}
[*] --> Init
	BLENotifierSC : c:gateway?set_base_color / \naction neopixels!setColor(c.rc.gc.b)\n
}
@enduml
