@startuml
skinparam defaultTextAlignment left
[*] --> GatewayCommandParserSC
state GatewayCommandParserSC{
state Ready{

Ready --> ParseCommand : m:blerx?receive_byte[m.b == '\'!\'']
}
state ParseCommand{

ParseCommand --> SetColor : m:blerx?receive_byte[m.b == '\'C\'']

ParseCommand --> Ready : m:blerx?receive_byte[m.b == '\'R\'']\naction gateway!request_measurement()\n

ParseCommand --> Ready : m:blerx?receive_byte[m.b == '\'G\'']\naction gateway!measurement_received()\n

ParseCommand --> Ready : m:blerx?receive_byte[m.b == '\'E\'']\naction gateway!bad_measurement()\n

ParseCommand --> Ready : m:blerx?receive_byte[m.b == '\'S\'']\naction gateway!measurement_stored()\n
}
state SetColor{
	SetColor : entry / idx = 0\n

SetColor --> Ready : m:blerx?receive_byte[idx == 2]\naction gateway!set_base_color(buf[0]buf[1]m.b)\n
	SetColor : m:blerx?receive_byte / [idx < 2]\naction do \n...\nend\n
}
[*] --> Ready
}
@enduml
