@startuml
skinparam defaultTextAlignment left
[*] --> NeoPixelStateChart
state NeoPixelStateChart{
state OFF{
	OFF : entry / do \n...\nend\n

OFF --> SOLID : ctrl?solid

OFF --> PULSE : ctrl?pulse

OFF --> BREATH : ctrl?breath

OFF --> ROTATE : m:ctrl?rotate\naction rotate_speed = m.speed\n
}
state SOLID{

SOLID --> OFF : ctrl?off
	SOLID : clock?fps_clock / \naction do \n...\nend\n
}
state ROTATE{

ROTATE --> OFF : ctrl?off
	ROTATE : clock?fps_clock / \naction do \n...\nend\n
}
state BREATH{

BREATH --> OFF : ctrl?off
	BREATH : clock?fps_clock / \naction do \n...\nend\n
}
state PULSE{

PULSE --> OFF : ctrl?off
	PULSE : clock?fps_clock / \naction do \n...\nend\n
}
[*] --> OFF
	NeoPixelStateChart : entry / initializeNeopixels()\n
	NeoPixelStateChart : c:ctrl?setColor / \naction do \n...\nend\n
}
@enduml
