@startuml
skinparam defaultTextAlignment left
[*] --> SerialImpl
state SerialImpl{
state Receiving{
	Receiving : entry / 'Serial.begin(9600);'\n
	Receiving : ['Serial.available()' > 0]\naction rx!receive_byte('(char)Serial.read()')\n
}
[*] --> Receiving
}
@enduml
