/*****************************************************
 *      THIS IS A GENERATED FILE. DO NOT EDIT.
 *       Definitions of datatypes and enums
 *  Generated from ThingML (http://www.thingml.org)
 *****************************************************/

#ifndef THINGML_TYPEDEFS_H_
#define THINGML_TYPEDEFS_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <stdint.h>
#include <stdbool.h>

// Definition of Enumeration  BLEAdvertisingType
#define BLEADVERTISINGTYPE_ADV_IND 0x00
#define BLEADVERTISINGTYPE_ADV_DIRECT_IND_HIGH 0x01
#define BLEADVERTISINGTYPE_ADV_SCAN_IND 0x02
#define BLEADVERTISINGTYPE_ADV_NONCONN_IND 0x03
#define BLEADVERTISINGTYPE_ADV_DIRECT_IND_LOW 0x05

// Definition of Enumeration  BLELinkRole
#define BLELINKROLE_MASTER 0x00
#define BLELINKROLE_SLAVE 0x01

// Definition of Enumeration  BTDisconnectReason
#define BTDISCONNECTREASON_AUTHENTICATION_FAILURE 0x05
#define BTDISCONNECTREASON_REMOTE_USER 0x13
#define BTDISCONNECTREASON_REMOTE_LOW_RESOURCES 0x14
#define BTDISCONNECTREASON_REMOTE_POWER_OFF 0x15
#define BTDISCONNECTREASON_UNSUPPORTED_REMOTE_FEATURE 0x1A
#define BTDISCONNECTREASON_UNIT_KEY_NOT_SUPPORTED 0x29
#define BTDISCONNECTREASON_UNACCEPTABLE_CONNECTION_PARAMETERS 0x3B

// Definition of Enumeration  SMPKeyDistribution
#define SMPKEYDISTRIBUTION_NOENCKEY_NOIDKEY_NOSIGN_NOLINKKEY 0x00
#define SMPKEYDISTRIBUTION_ENCKEY_NOIDKEY_NOSIGN_NOLINKKEY 0x01
#define SMPKEYDISTRIBUTION_NOENCKEY_IDKEY_NOSIGN_NOLINKKEY 0x02
#define SMPKEYDISTRIBUTION_ENCKEY_IDKEY_NOSIGN_NOLINKKEY 0x03
#define SMPKEYDISTRIBUTION_NOENCKEY_NOIDKEY_SIGN_NOLINKKEY 0x04
#define SMPKEYDISTRIBUTION_ENCKEY_NOIDKEY_SIGN_NOLINKKEY 0x05
#define SMPKEYDISTRIBUTION_NOENCKEY_IDKEY_SIGN_NOLINKKEY 0x06
#define SMPKEYDISTRIBUTION_ENCKEY_IDKEY_SIGN_NOLINKKEY 0x07
#define SMPKEYDISTRIBUTION_NOENCKEY_NOIDKEY_NOSIGN_LINKKEY 0x08
#define SMPKEYDISTRIBUTION_ENCKEY_NOIDKEY_NOSIGN_LINKKEY 0x09
#define SMPKEYDISTRIBUTION_NOENCKEY_IDKEY_NOSIGN_LINKKEY 0x0A
#define SMPKEYDISTRIBUTION_ENCKEY_IDKEY_NOSIGN_LINKKEY 0x0B
#define SMPKEYDISTRIBUTION_NOENCKEY_NOIDKEY_SIGN_LINKKEY 0x0C
#define SMPKEYDISTRIBUTION_ENCKEY_NOIDKEY_SIGN_LINKKEY 0x0D
#define SMPKEYDISTRIBUTION_NOENCKEY_IDKEY_SIGN_LINKKEY 0x0E
#define SMPKEYDISTRIBUTION_ENCKEY_IDKEY_SIGN_LINKKEY 0x0F

// Definition of Enumeration  BLEAdvertisementReportType
#define BLEADVERTISEMENTREPORTTYPE_ADV_IND 0x00
#define BLEADVERTISEMENTREPORTTYPE_ADV_DIRECT_IND 0x01
#define BLEADVERTISEMENTREPORTTYPE_ADV_SCAN_IND 0x02
#define BLEADVERTISEMENTREPORTTYPE_ADV_NONCONN_IND 0x03
#define BLEADVERTISEMENTREPORTTYPE_SCAN_RSP 0x04

// Definition of Enumeration  BLEAdvertisingFilterPolicy
#define BLEADVERTISINGFILTERPOLICY_ALL 0x00
#define BLEADVERTISINGFILTERPOLICY_CONN_ALL_SCAN_WHITELIST 0x01
#define BLEADVERTISINGFILTERPOLICY_CONN_WHITELIST_SCAN_ALL 0x02
#define BLEADVERTISINGFILTERPOLICY_CONN_SCAN_WHITELIST 0x03

// Definition of Enumeration  BLEAdvertisingChannel
#define BLEADVERTISINGCHANNEL_CHANNEL_37 0x01
#define BLEADVERTISINGCHANNEL_CHANNEL_38 0x02
#define BLEADVERTISINGCHANNEL_CHANNEL_39 0x04
#define BLEADVERTISINGCHANNEL_ALL 0x07

// Definition of Enumeration  BLEAddressType
#define BLEADDRESSTYPE_PUBLIC 0x00
#define BLEADDRESSTYPE_RANDOM 0x01

// Definition of Enumeration  BLEScanFilterPolicy
#define BLESCANFILTERPOLICY_ALL 0x00
#define BLESCANFILTERPOLICY_ONLY_FROM_WHITELISTED 0x01
#define BLESCANFILTERPOLICY_DIRECTED_RESOLVABLE 0x02
#define BLESCANFILTERPOLICY_DIRECTED_RESOLVABLE_WHITELISTED 0x03

// Definition of Enumeration  SMPPairingFailReason
#define SMPPAIRINGFAILREASON_PASSKEY_ENTRY_FAILED 0x01
#define SMPPAIRINGFAILREASON_OOB_NOT_AVAILABLE 0x02
#define SMPPAIRINGFAILREASON_AUTHENTICATION_REQUIREMENTS 0x03
#define SMPPAIRINGFAILREASON_CONFIRM_VALUE_FAILED 0x03
#define SMPPAIRINGFAILREASON_PAIRING_NOT_SUPPORTED 0x04
#define SMPPAIRINGFAILREASON_ENCRYPTION_KEY_SIZE 0x06
#define SMPPAIRINGFAILREASON_COMMAND_NOT_SUPPORTED 0x07
#define SMPPAIRINGFAILREASON_UNSPECIFIED 0x08
#define SMPPAIRINGFAILREASON_REPEATED_ATTEMPTS 0x09
#define SMPPAIRINGFAILREASON_INVALID_PARAMETERS 0x0A
#define SMPPAIRINGFAILREASON_DHKEY_FAILED 0x0B
#define SMPPAIRINGFAILREASON_NUMERIC_COMPARISON_FAILED 0x0C
#define SMPPAIRINGFAILREASON_BREDR_PAIRING_PROGRESS 0x0D
#define SMPPAIRINGFAILREASON_CROSS_TRANSPORT_KEY 0x0E

// Definition of Enumeration  ACLPacketBoundaryFlag
#define ACLPACKETBOUNDARYFLAG_FIRST_NOFLUSH 0x00
#define ACLPACKETBOUNDARYFLAG_CONT_FRAGMENT 0x01
#define ACLPACKETBOUNDARYFLAG_FIRST_FLUSHABLE 0x02
#define ACLPACKETBOUNDARYFLAG_COMPLETE 0x03

// Definition of Enumeration  SMPKeypressNotification
#define SMPKEYPRESSNOTIFICATION_ENTRY_STARTED 0x00
#define SMPKEYPRESSNOTIFICATION_DIGIT_ENTERED 0x01
#define SMPKEYPRESSNOTIFICATION_DIGIT_ERASED 0x02
#define SMPKEYPRESSNOTIFICATION_CLEARED 0x03
#define SMPKEYPRESSNOTIFICATION_ENTRY_COMPLETED 0x04

// Definition of Enumeration  BLEInitiatorFilterPolicy
#define BLEINITIATORFILTERPOLICY_WHITELIST_NOT_USED 0x00
#define BLEINITIATORFILTERPOLICY_WHITELIST_USED 0x01

// Definition of Enumeration  Device
#define DEVICE_NONE 0x00
#define DEVICE_ANDUC352BLE 0x01
#define DEVICE_ANDUA651BLE 0x02

// Definition of Enumeration  ACLBroadcastFlag
#define ACLBROADCASTFLAG_POINTTOPOINT 0x00
#define ACLBROADCASTFLAG_ACTIVE_SLAVE 0x01
#define ACLBROADCASTFLAG_PARKED_SLAVE 0x02

// Definition of Enumeration  BLEScanType
#define BLESCANTYPE_PASSIVE 0x00
#define BLESCANTYPE_ACTIVE 0x01

// Definition of Enumeration  SMPIOCapabilities
#define SMPIOCAPABILITIES_DISPLAY_ONLY 0x00
#define SMPIOCAPABILITIES_DISPLAY_YESNO 0x01
#define SMPIOCAPABILITIES_KEYBOARD_ONLY 0x02
#define SMPIOCAPABILITIES_NO_INPUT_NO_OUTPUT 0x03
#define SMPIOCAPABILITIES_KEYBOARD_DISPLAY 0x04

// Definition of Enumeration  ATTErrorCode
#define ATTERRORCODE_INVALID_HANDLE 0x01
#define ATTERRORCODE_READ_NOT_PERMITTED 0x02
#define ATTERRORCODE_WRITE_NOT_PERMITTED 0x03
#define ATTERRORCODE_INVALID_PDU 0x04
#define ATTERRORCODE_INSUFFICIENT_AUTHENTICATION 0x05
#define ATTERRORCODE_REQUEST_NOT_SUPPORTED 0x06
#define ATTERRORCODE_INVALID_OFFSET 0x07
#define ATTERRORCODE_INSUFFICIENT_AUTHORIZATION 0x08
#define ATTERRORCODE_PREPARE_QUEUE_FULL 0x09
#define ATTERRORCODE_ATTRIBUTE_NOT_FOUND 0x0A
#define ATTERRORCODE_ATTRIBUTE_NOT_LONG 0x0B
#define ATTERRORCODE_INSUFFICIENT_ENCRYPTION_KEY_SIZE 0x0C
#define ATTERRORCODE_INVALID_ATTRIBUTE_VALUE_LENGTH 0x0D
#define ATTERRORCODE_UNLIKELY_ERROR 0x0E
#define ATTERRORCODE_INSUFICIENT_ENCRYPTION 0x0F
#define ATTERRORCODE_UNSUPPORTED_GROUP_TYPE 0x10
#define ATTERRORCODE_INSUFICIENT_RESOURCES 0x11



/*typedef unsigned char  uint8;
typedef unsigned short uint16;
typedef signed short   int16;
typedef unsigned long  uint32;
typedef signed char    int8;*/


#ifdef __cplusplus
}
#endif

#endif //THINGML_TYPEDEFS_H_
